- title: Blockchain Development - NFt Minting - Exchange Building - Smart Contract development - IEO - DAPP 
  icon: "/services/branding.svg"
  description: I can build everything from a token to an nft - to a full scale nft marketplace -  like open sea!
- title: Full Stack Development - web apps / ios apps / android apps/ scripting / API 
  icon: "/services/uix.svg"
  description: I'm great at building complex production ready applications. It doesn't matter if they are web based or native. 
- title: Growth Hacking
  icon: "/services/dev.svg"
  description: Bot the social networks, email mine, etc. 
- title: SEO & growth
  icon: "/services/seo.svg"
  description: Your ranking on search engines will improve and growth hacking strategies will be tested and reported to keep you ahead of your competitors.
